#!/usr/bin/env python3
"""Build Phase 1a's original static UFO → Designspace → TTF/OTF/WOFF2 pipeline."""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
import shutil
import subprocess
import sys

from fontTools import __version__ as fonttools_version
from fontTools.designspaceLib import DesignSpaceDocument, SourceDescriptor
from fontTools.ttLib import TTFont
from ufoLib2 import Font

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from fontlab.recipes import evaluate_project, load_project, source_hash  # noqa: E402

BUILD = ROOT / "build"
SOURCES = BUILD / "sources"
FONTS = BUILD / "fonts"
MANIFEST = BUILD / "manifest.json"


def draw_contour(pen, contour):
    for command in contour:
        operator, values = command[0], command[1:]
        if operator == "M":
            pen.moveTo((values[0], values[1]))
        elif operator == "L":
            pen.lineTo((values[0], values[1]))
        elif operator == "C":
            pen.curveTo((values[0], values[1]), (values[2], values[3]), (values[4], values[5]))
        elif operator == "Z":
            pen.closePath()
        else:  # The evaluator guarantees this, but never silently accept a new command here.
            raise ValueError(f"unsupported path command {operator}")


def build_ufo(evaluated: dict) -> Path:
    ufo_path = SOURCES / "PFLTechnicalSansPhase1a-Regular.ufo"
    font = Font()
    font.info.familyName = "PFL Technical Sans Phase 1a"
    font.info.styleName = "Regular"
    font.info.postscriptFontName = "PFLTechnicalSansPhase1a-Regular"
    font.info.unitsPerEm = 1000
    font.info.ascender = 800
    font.info.descender = -200
    font.info.capHeight = 700
    font.info.xHeight = 500
    font.info.openTypeOS2WeightClass = 400
    font.info.openTypeNameVersion = "Version 0.1"
    font.info.copyright = "Original contours generated by Parametric Font Lab"
    font.info.openTypeNameLicense = "Original project source; no third-party font outlines included."

    missing = font.newGlyph(".notdef")
    missing.width = 680
    pen = missing.getPen()
    pen.moveTo((70, 0)); pen.lineTo((610, 0)); pen.lineTo((610, 700)); pen.lineTo((70, 700)); pen.closePath()
    pen.moveTo((130, 60)); pen.lineTo((550, 60)); pen.lineTo((550, 640)); pen.lineTo((130, 640)); pen.closePath()
    space = font.newGlyph("space")
    space.width = 280
    space.unicodes = [0x20]
    for glyph_data in evaluated["glyphs"]:
        glyph = font.newGlyph(glyph_data["name"])
        glyph.width = glyph_data["advance"]
        glyph.unicodes = [glyph_data["unicode"]]
        pen = glyph.getPen()
        for contour in glyph_data["contours"]:
            draw_contour(pen, contour)
    font.save(ufo_path, overwrite=True)
    return ufo_path


def build_designspace(ufo_path: Path) -> Path:
    designspace_path = SOURCES / "PFLTechnicalSansPhase1a.designspace"
    document = DesignSpaceDocument()
    source = SourceDescriptor()
    source.name = "Regular"
    source.path = str(ufo_path.resolve())
    source.familyName = "PFL Technical Sans Phase 1a"
    source.styleName = "Regular"
    source.copyInfo = True
    source.copyLib = True
    source.copyGroups = True
    source.copyFeatures = True
    document.addSource(source)
    document.write(designspace_path)
    return designspace_path


def compile_static(designspace_path: Path) -> list[Path]:
    outputs = []
    for format_name in ("ttf", "otf"):
        subprocess.run(
            [sys.executable, "-m", "fontmake", "-m", str(designspace_path), "-o", format_name, "--output-dir", str(FONTS)],
            check=True,
            cwd=ROOT,
        )
        outputs.extend(sorted(FONTS.glob(f"*.{format_name}")))
    return outputs


def compress_woff2(ttf_paths: list[Path]) -> list[Path]:
    outputs = []
    for ttf_path in ttf_paths:
        font = TTFont(ttf_path)
        font.flavor = "woff2"
        woff2_path = ttf_path.with_suffix(".woff2")
        font.save(woff2_path)
        outputs.append(woff2_path)
    return outputs


def validate_outputs(paths: list[Path], expected_glyphs: list[dict]) -> None:
    expected_cmap = {glyph["unicode"]: glyph["name"] for glyph in expected_glyphs}
    required_tables = {"head", "hhea", "maxp", "cmap", "name"}
    for path in paths:
        font = TTFont(path)
        if not required_tables.issubset(font.keys()):
            raise RuntimeError(f"{path.name}: missing required tables")
        if not ({"glyf", "CFF ", "CFF2"} & set(font.keys())):
            raise RuntimeError(f"{path.name}: missing a glyph-outline table")
        cmap = font.getBestCmap()
        if {codepoint: cmap.get(codepoint) for codepoint in expected_cmap} != expected_cmap:
            raise RuntimeError(f"{path.name}: cmap differs from source")
        for glyph_name in expected_cmap.values():
            if glyph_name not in font.getGlyphOrder():
                raise RuntimeError(f"{path.name}: missing {glyph_name}")


def main() -> None:
    project = load_project()
    evaluated = evaluate_project(project)
    if BUILD.exists():
        shutil.rmtree(BUILD)
    SOURCES.mkdir(parents=True)
    FONTS.mkdir(parents=True)
    ufo_path = build_ufo(evaluated)
    designspace_path = build_designspace(ufo_path)
    compiled = compile_static(designspace_path)
    woff2 = compress_woff2([path for path in compiled if path.suffix == ".ttf"])
    validate_outputs([*compiled, *woff2], evaluated["glyphs"])
    manifest = {
        "project": project["id"],
        "sourceHash": source_hash(project),
        "compiler": {"fontTools": fonttools_version, "python": sys.version.split()[0]},
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "ufo": str(ufo_path.relative_to(ROOT)),
        "designspace": str(designspace_path.relative_to(ROOT)),
        "fonts": [str(path.relative_to(ROOT)) for path in [*compiled, *woff2]],
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
