#!/usr/bin/env python3
"""Build versioned static UFO → Designspace → TTF/OTF/WOFF2 instances."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from hashlib import sha256
from html import escape
import json
from pathlib import Path
import subprocess
import sys

from fontTools import __version__ as fonttools_version
from fontTools.designspaceLib import DesignSpaceDocument, SourceDescriptor
from fontTools.pens.areaPen import AreaPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.ttLib import TTFont
from ufoLib2 import Font

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from fontlab.recipes import KERNING_GROUPS, PROJECT_PATH, evaluate_project, kerning_value, load_project, source_hash  # noqa: E402
from fontlab.identity import build_id, engine_hash  # noqa: E402

BUILD = ROOT / "build"


def draw_contour(pen, contour):
    for command in contour:
        operator, values = command[0], command[1:]
        if operator == "M":
            pen.moveTo((values[0], values[1]))
        elif operator == "L":
            pen.lineTo((values[0], values[1]))
        elif operator == "C":
            pen.curveTo((values[0], values[1]), (values[2], values[3]), (values[4], values[5]))
        elif operator == "Z":
            pen.closePath()
        else:  # The evaluator guarantees this, but never silently accept a new command here.
            raise ValueError(f"unsupported path command {operator}")


def style_name(project: dict) -> str:
    axes = project["axes"]
    return f"W{axes['weight']:g} Wd{axes['width'] * 100:g} X{axes['xHeight']:g} {project['switches']['aConstruction'].title()} {project['switches']['zeroStyle'].title()}"


def build_ufo(evaluated: dict, project: dict, sources: Path, instance_name: str) -> Path:
    ufo_path = sources / f"{instance_name}.ufo"
    font = Font()
    font.info.familyName = "PFL Technical Sans Type Quality" if project["schemaVersion"] == 2 else "PFL Technical Sans Phase 1b"
    weight = project["axes"]["weight"]
    font.info.styleName = style_name(project)
    font.info.postscriptFontName = instance_name
    font.info.unitsPerEm = 1000
    font.info.ascender = 800
    font.info.descender = -200
    font.info.capHeight = 700
    font.info.xHeight = project["axes"]["xHeight"]
    font.info.openTypeOS2WeightClass = round(100 + (weight - 40) / 120 * 800)
    font.info.openTypeNameVersion = f"Version {project['engine']['version']}"
    font.info.copyright = "Original contours generated by Parametric Font Lab"
    font.info.openTypeNameLicense = "Original project source; no third-party font outlines included."

    missing = font.newGlyph(".notdef")
    missing.width = 680
    pen = missing.getPen()
    pen.moveTo((70, 0)); pen.lineTo((610, 0)); pen.lineTo((610, 700)); pen.lineTo((70, 700)); pen.closePath()
    pen.moveTo((130, 60)); pen.lineTo((550, 60)); pen.lineTo((550, 640)); pen.lineTo((130, 640)); pen.closePath()
    for glyph_data in evaluated["glyphs"]:
        glyph = font.newGlyph(glyph_data["name"])
        glyph.width = glyph_data["advance"]
        glyph.unicodes = [glyph_data["unicode"]]
        pen = glyph.getPen()
        for contour in glyph_data["contours"]:
            draw_contour(pen, contour)
        for anchor_name, position in glyph_data["anchors"].items():
            glyph.appendAnchor({"name": anchor_name, "x": position[0], "y": position[1]})
    for group_name, members in KERNING_GROUPS.items():
        font.groups[group_name] = members
    for pair, value in evaluated["kerning"].items():
        font.kerning[pair] = value
    font.save(ufo_path, overwrite=True)
    return ufo_path


def build_designspace(ufo_path: Path, sources: Path, style_name: str, project: dict) -> Path:
    designspace_path = sources / "PFLTechnicalSans.designspace"
    document = DesignSpaceDocument()
    source = SourceDescriptor()
    source.name = "Regular"
    source.path = str(ufo_path.resolve())
    source.familyName = "PFL Technical Sans Type Quality" if project["schemaVersion"] == 2 else "PFL Technical Sans Phase 1b"
    source.styleName = style_name
    source.copyInfo = True
    source.copyLib = True
    source.copyGroups = True
    source.copyFeatures = True
    document.addSource(source)
    document.write(designspace_path)
    return designspace_path


def compile_static(designspace_path: Path, fonts: Path, instance_name: str) -> list[Path]:
    outputs = []
    for format_name in ("ttf", "otf"):
        subprocess.run(
            [sys.executable, "-m", "fontmake", "-m", str(designspace_path), "-o", format_name, "--output-dir", str(fonts)],
            check=True,
            cwd=ROOT,
            timeout=60,
        )
        output = fonts / f"{instance_name}.{format_name}"
        if not output.is_file():
            raise RuntimeError(f"fontmake did not create {output.name}")
        outputs.append(output)
    return outputs


def compress_woff2(ttf_paths: list[Path]) -> list[Path]:
    outputs = []
    for ttf_path in ttf_paths:
        font = TTFont(ttf_path)
        font.flavor = "woff2"
        woff2_path = ttf_path.with_suffix(".woff2")
        font.save(woff2_path)
        outputs.append(woff2_path)
    return outputs


def validate_outputs(paths: list[Path], expected_glyphs: list[dict], pairs: dict, version: int) -> None:
    expected_cmap = {glyph["unicode"]: glyph["name"] for glyph in expected_glyphs}
    expected_advances = {glyph["name"]: glyph["advance"] for glyph in expected_glyphs}
    proof_pairs = (("A", "O"), ("A", "V"), ("V", "A"), ("T", "O"), ("T", "a"), ("T", "o"), ("uni0410", "uni041E"), ("uni0422", "uni0410"), ("uni0422", "uni0430"), ("uni0422", "uni043E"))
    expected_kerning = {pair: kerning_value(*pair, pairs) for pair in proof_pairs}

    def pair_adjustment(font: TTFont, left: str, right: str) -> int | None:
        for lookup in font["GPOS"].table.LookupList.Lookup:
            if lookup.LookupType != 2:
                continue
            for subtable in lookup.SubTable:
                if left not in subtable.Coverage.glyphs:
                    continue
                if subtable.Format == 1:
                    pair_set = subtable.PairSet[subtable.Coverage.glyphs.index(left)]
                    for record in pair_set.PairValueRecord:
                        if record.SecondGlyph == right:
                            return getattr(record.Value1, "XAdvance", 0) or 0
                elif subtable.Format == 2:
                    class1 = subtable.ClassDef1.classDefs.get(left, 0)
                    class2 = subtable.ClassDef2.classDefs.get(right, 0)
                    record = subtable.Class1Record[class1].Class2Record[class2]
                    return getattr(record.Value1, "XAdvance", 0) or 0
        return None

    required_tables = {"head", "hhea", "maxp", "cmap", "name", "GPOS"}
    for path in paths:
        font = TTFont(path)
        if not required_tables.issubset(font.keys()):
            raise RuntimeError(f"{path.name}: missing required tables")
        if not ({"glyf", "CFF ", "CFF2"} & set(font.keys())):
            raise RuntimeError(f"{path.name}: missing a glyph-outline table")
        cmap = font.getBestCmap()
        if {codepoint: cmap.get(codepoint) for codepoint in expected_cmap} != expected_cmap:
            raise RuntimeError(f"{path.name}: cmap differs from source")
        for glyph_name in expected_cmap.values():
            if glyph_name not in font.getGlyphOrder():
                raise RuntimeError(f"{path.name}: missing {glyph_name}")
            if font["hmtx"].metrics[glyph_name][0] != expected_advances[glyph_name]:
                raise RuntimeError(f"{path.name}: advance for {glyph_name} differs from source")
        glyph_set = font.getGlyphSet()
        for glyph_name, flat_top in (("O", 700), ("uni041E", 700), ("C", 700), ("uni0421", 700),
                                     ("zero", 700), ("o", font["OS/2"].sxHeight),
                                     ("uni043E", font["OS/2"].sxHeight), ("c", font["OS/2"].sxHeight),
                                     ("uni0441", font["OS/2"].sxHeight)):
            bounds_pen = BoundsPen(glyph_set)
            glyph_set[glyph_name].draw(bounds_pen)
            if bounds_pen.bounds is None or bounds_pen.bounds[1] > -9 or bounds_pen.bounds[3] < flat_top + 9:
                raise RuntimeError(f"{path.name}: {glyph_name} lost its optical overshoot")
        if not any(lookup.LookupType == 2 for lookup in font["GPOS"].table.LookupList.Lookup):
            raise RuntimeError(f"{path.name}: missing pair kerning lookup")
        if not any(lookup.LookupType == 4 for lookup in font["GPOS"].table.LookupList.Lookup):
            raise RuntimeError(f"{path.name}: missing mark attachment lookup")
        for pair, value in expected_kerning.items():
            if pair_adjustment(font, *pair) != value:
                raise RuntimeError(f"{path.name}: kerning for {pair[0]}/{pair[1]} differs from source")
        glyph_set = font.getGlyphSet()
        drawings = {}
        for glyph_name in ("A", "U", "h", "n", "uni0414", "uni041B", "b", "uni044C"):
            pen = RecordingPen()
            glyph_set[glyph_name].draw(pen)
            drawings[glyph_name] = pen.value
        if font["hmtx"].metrics["h"][0] == font["hmtx"].metrics["n"][0] or drawings["h"] == drawings["n"]:
            raise RuntimeError(f"{path.name}: h and n remain indistinguishable")
        if version == 2:
            if drawings["uni0414"] == drawings["uni041B"] or drawings["b"] == drawings["uni044C"]:
                raise RuntimeError(f"{path.name}: control glyphs remain indistinguishable")
            for name, minimum, maximum in (("b", 690, None), ("uni044C", None, 560)):
                bounds_pen = BoundsPen(glyph_set)
                glyph_set[name].draw(bounds_pen)
                if bounds_pen.bounds is None or (minimum is not None and bounds_pen.bounds[3] < minimum) or (maximum is not None and bounds_pen.bounds[3] > maximum):
                    raise RuntimeError(f"{path.name}: {name} has incorrect ascender height")
        if sum(operator == "moveTo" for operator, _ in drawings["U"]) != 1:
            raise RuntimeError(f"{path.name}: U stems did not compile into one connected outline")
        if sum(operator == "moveTo" for operator, _ in drawings["A"]) != 2:
            raise RuntimeError(f"{path.name}: A must compile to one outer outline and one intentional counter")
        areas = []
        pen = None
        for operator, values in drawings["A"]:
            if operator == "moveTo":
                pen = AreaPen()
                pen.moveTo(values[0])
            elif operator == "lineTo":
                pen.lineTo(values[0])
            elif operator == "curveTo":
                pen.curveTo(*values)
            elif operator == "closePath":
                pen.closePath()
                areas.append(pen.value)
        if len(areas) != 2 or areas[0] * areas[1] >= 0:
            raise RuntimeError(f"{path.name}: A counter winding is invalid")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a static font from a versioned project JSON file.")
    parser.add_argument("--project", type=Path, default=PROJECT_PATH, help="Project JSON exported by the browser (default: fontlab/project.json)")
    parser.add_argument("--output-dir", type=Path, default=BUILD, help="Directory for generated instances (default: build)")
    args = parser.parse_args()
    raw = args.project.read_bytes()
    if len(raw) > 65536:
        raise ValueError("project exceeds 65536 bytes")
    raw_project = json.loads(raw.decode("utf-8"))
    if not isinstance(raw_project, dict):
        raise ValueError("project JSON must be an object")
    if raw_project.get("schemaVersion") == 3:
        from tools.build_inter_font import build_inter_font
        from fontlab.inter_source import load_project as load_inter_project
        build_inter_font(load_inter_project(args.project), args.output_dir.resolve())
        return
    project = load_project(args.project)
    evaluated = evaluate_project(project)
    project_hash = source_hash(project)
    revision = engine_hash()
    identity = build_id(project_hash, revision)
    instance_name = f"PFLTechnicalSans-{identity[:12]}"
    instance = args.output_dir.resolve() / identity
    sources = instance / "sources"
    fonts = instance / "fonts"
    sources.mkdir(parents=True, exist_ok=True)
    fonts.mkdir(parents=True, exist_ok=True)
    ufo_path = build_ufo(evaluated, project, sources, instance_name)
    designspace_path = build_designspace(ufo_path, sources, style_name(project), project)
    compiled = compile_static(designspace_path, fonts, instance_name)
    woff2 = compress_woff2([path for path in compiled if path.suffix == ".ttf"])
    validate_outputs([*compiled, *woff2], evaluated["glyphs"], evaluated["kerning"], project["schemaVersion"])
    binary_hashes = {str(path.relative_to(instance)): sha256(path.read_bytes()).hexdigest() for path in [*compiled, *woff2]}
    control_text = "H O A V C S n o b d e | Н О С Д Л Ж К Я и н о п б д л е ь\nbone done | нос сон дно поле дело | AV VA AO АО ДО ДЛ b ь"
    proof_rows = "".join(f'<div class="proof" style="font-size:{size}px"><span class="size">{size} px</span>{escape(control_text)}</div>' for size in (10,14,24,72))
    proof_html = f'''<!doctype html><html lang="en"><meta charset="utf-8"><title>Compiled PFL proof {identity[:12]}</title>
<style>body{{font-family:Arial,sans-serif;margin:24px}}.proof{{white-space:pre-wrap;line-height:1.45;margin:18px 0;display:none}}.size{{display:block;font:12px Arial;color:#555}}body[data-proof-state="ready"] .proof{{display:block;font-family:PFLCompiled}}#status[data-error]{{color:#b5121b}}</style>
<h1>Compiled font proof</h1><p>Project: {escape(project['id'])} · Source: {project_hash[:16]} · Engine: {revision[:16]}</p>
<p id="status" role="status">Loading compiled WOFF2…</p>{proof_rows}
<script>const face=new FontFace('PFLCompiled','url(./fonts/{woff2[0].name}) format("woff2")');
face.load().then(font=>{{document.fonts.add(font);document.body.dataset.proofState='ready';document.getElementById('status').textContent='Compiled WOFF2 loaded';}}).catch(error=>{{document.body.dataset.proofState='error';let status=document.getElementById('status');status.dataset.error='';status.textContent='Compiled font failed to load: '+error.message;}});</script></html>'''
    (instance / "proof.html").write_text(proof_html, encoding="utf-8")
    manifest = {
        "project": project["id"],
        "sourceHash": project_hash,
        "engineHash": revision,
        "buildId": identity,
        "instanceName": instance_name,
        "compiler": {"fontTools": fonttools_version, "python": sys.version.split()[0]},
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "ufo": str(ufo_path.relative_to(instance)),
        "designspace": str(designspace_path.relative_to(instance)),
        "fonts": [str(path.relative_to(instance)) for path in [*compiled, *woff2]],
        "binaryHashes": binary_hashes,
        "proof": "proof.html",
        "proofHash": sha256(proof_html.encode("utf-8")).hexdigest(),
    }
    (instance / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
