const K=.5522847498307936, caps='ABCDEFGHIJKLMNOPQRSTUVWXYZ', lows='abcdefghijklmnopqrstuvwxyz', cu='АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ', cl='абвгдеёжзийклмнопрстуфхцчшщъыьэюя';
let project, glyphs=[], selected='A', snapshot=null;
const state={weight:88,width:1,xHeight:500,roundness:.74,aperture:.58,counter:1,construction:'double',zeroStyle:'plain',preset:'text'};
const S=(tag,a={})=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e};
const rect=(x,y,X,Y)=>[['M',x,y],['L',X,y],['L',X,Y],['L',x,Y],['Z']];
const oval=(x,y,rx,ry,rev=false)=>{let k=.18+.3722847498307936*state.roundness;let q=[['M',x+rx,y],['C',x+rx,y+k*ry,x+k*rx,y+ry,x,y+ry],['C',x-k*rx,y+ry,x-rx,y+k*ry,x-rx,y],['C',x-rx,y-k*ry,x-k*rx,y-ry,x,y-ry],['C',x+k*rx,y-ry,x+rx,y-k*ry,x+rx,y],['Z']];return rev?[['M',x+rx,y],['C',x+rx,y-k*ry,x+k*rx,y-ry,x,y-ry],['C',x-k*rx,y-ry,x-rx,y-k*ry,x-rx,y],['C',x-rx,y+k*ry,x-k*rx,y+ry,x,y+ry],['C',x+k*rx,y+ry,x+rx,y+k*ry,x+rx,y],['Z']]:q};
const ring=(x,y,rx,ry,w)=>[oval(x,y,rx,ry),oval(x,y,rx-w,ry-w,true)];
const stroke=(x,y,X,Y,w)=>{let d=Math.hypot(X-x,Y-y),p=-(Y-y)/d*w/2,q=(X-x)/d*w/2;return [['M',x+p,y+q],['L',X+p,Y+q],['L',X-p,Y-q],['L',x-p,y-q],['Z']]};
const adv=g=>g.mark?0:g.char===' '||g.char===' '?280:g.kind==='common'?360:g.kind==='digit'?620:g.upper?(g.char.match(/[MWЖШЩЮ]/)?820:g.char.match(/[IЛ]/)?420:680):(g.char.match(/[mwжшщю]/)?760:g.char.match(/[ilт]/)?330:540);
function shape(g){let a=adv(g),w=state.weight,h=g.upper?700:state.xHeight,l=80,r=a-80,m=a/2,c=g.char;let v=x=>rect(x-w/2,0,x+w/2,h),bar=y=>rect(l,y-w/2,r,y+w/2),generic=()=>[v(l),v(r),bar(h),bar(0)];if(g.mark)return c==='́'?[stroke(180,720,340,890,w*.5)]:[...ring(180,800,w*.52,w*.52,w*.28),...ring(340,800,w*.52,w*.52,w*.28)];if(g.kind==='common'){if(c===' '||c===' ')return [];if('-_'.includes(c))return [bar(c==='-'?350:0)];if('/\\'.includes(c))return [stroke(a*.25,0,a*.75,700,w)];return [rect(m-w/2,0,m+w/2,700)]}if(g.kind==='digit'){if(c==='0')return [...ring(m,350,a*.34,350,w+8),...(state.zeroStyle==='slashed'?[stroke(a*.27,85,a*.73,615,w*.5)]:[])];return generic()}if('OoОоФфЮю'.includes(c))return [...ring(m,h/2,a*.36,h*.48,w+(c==='O'?24*(1-state.counter):0)),...('Фф'.includes(c)?[v(m)]:[])];if(c==='a'&&state.construction==='single')return [...ring(a*.46,h*.42,a*.29,h*.38,w),rect(a*.72-w,0,a*.72,h)];if('HН'.includes(c))return [v(l),v(r),bar(h/2)];if('AEFЕ'.includes(c))return [v(l),bar(h),bar(h/2),bar(0)];if('XxЖж'.includes(c))return [stroke(l,0,r,h,w),stroke(l,h,r,0,w)];if('ДЛл'.includes(c))return [bar(0),stroke(l,0,m,h,w),stroke(r,0,m,h,w)];if('УуYy'.includes(c))return [stroke(l,h,m,h*.35,w),stroke(r,h,m,h*.35,w),stroke(m,h*.35,l,-180,w)];if('Ёё'.includes(c))return [v(l),bar(h),bar(h/2),bar(0),...ring(a*.36,h+90,w*.5,w*.5,w*.28),...ring(a*.64,h+90,w*.5,w*.5,w*.28)];return generic()}
function evalGlyph(g){let a=Math.round(adv(g)*state.width),q=shape(g).map(z=>z.map(c=>c[0]==='Z'?c:[c[0],...c.slice(1).map((v,i)=>i%2===0?v*state.width:v)]));return {...g,advance:a,contours:q}}
const path=q=>q.map(c=>c[0]==='Z'?'Z':`${c[0]} ${c.slice(1).map(x=>Number(x.toFixed(3))).join(' ')}`).join(' ');
function svgGlyph(g){let x=S('svg',{class:'glyph',viewBox:`0 -180 ${g.advance||280} 1100`,'data-glyph-id':g.id}),p=S('path',{d:g.contours.map(path).join(' '),'fill-rule':'nonzero'});x.append(p);return x}
const name=(c)=>c===' '?'space':c===' '?'nbspace':/^[A-Za-z]$/.test(c)?c:/^\d$/.test(c)?['zero','one','two','three','four','five','six','seven','eight','nine'][+c]:c==='́'?'acutecomb':c==='̈'?'dieresiscomb':`uni${c.codePointAt(0).toString(16).padStart(4,'0').toUpperCase()}`;
function render(){let current=evalGlyph(glyphs.find(x=>x.char===selected));document.querySelector('#selected-name').textContent=selected;let out=document.querySelector('#outline');out.replaceChildren(S('path',{d:current.contours.map(path).join(' '),'fill-rule':'nonzero'}));let chart=document.querySelector('#chart');chart.replaceChildren();glyphs.forEach(g=>{let b=document.createElement('button');b.type='button';b.className='glyph-button';b.dataset.glyph=g.name;b.textContent=g.char;b.onclick=()=>{selected=g.char;render()};chart.append(b)});let p=document.querySelector('#specimen-preview');p.replaceChildren();let bad=[];let prev=null;for(let c of document.querySelector('#specimen').value){let g=glyphs.find(x=>x.char===c);if(c==='\n'){p.append(document.createElement('br'));prev=null}else if(g){let e=svgGlyph(evalGlyph(g));if(prev&&'AVАВДЛТУ'.includes(prev)&&'OoОо'.includes(c))e.style.marginLeft='-5px';p.append(e);prev=c}else if(!/\s/.test(c))bad.push(c)}document.querySelector('#preview-error').textContent=bad.length?`Outside the Phase 1b repertoire: ${[...new Set(bad)].join(' ')}`:'';Object.entries(state).forEach(([k,v])=>{let e=document.querySelector(`#${k}`);if(e)e.value=v});document.querySelector('#zero-style').value=state.zeroStyle;document.querySelector('#download-project').disabled=false}
function currentProject(){return {...project,activePreset:state.preset,axes:{weight:state.weight,width:state.width,xHeight:state.xHeight,roundness:state.roundness,aperture:state.aperture},localOverrides:{O:{counter:state.counter}},switches:{aConstruction:state.construction,zeroStyle:state.zeroStyle}}}
const presets={text:{weight:88,width:1,xHeight:500,roundness:.74,aperture:.58,construction:'double',zeroStyle:'plain'},display:{weight:124,width:1.08,xHeight:520,roundness:.9,aperture:.72,construction:'single',zeroStyle:'slashed'}};
function controls(){let host=document.querySelector('#axis-controls');[['weight',40,160,1],['width',.85,1.15,.01],['xHeight',460,540,1],['roundness',0,1,.01],['aperture',0,1,.01]].forEach(([id,min,max,step])=>{let d=document.createElement('div');d.innerHTML=`<label for="${id}-number">${id}</label><div class="axis-inputs"><input id="${id}" type="range" min="${min}" max="${max}" step="${step}"><input id="${id}-number" type="number" min="${min}" max="${max}" step="${step}"></div>`;host.append(d);[d.querySelector(`#${id}`),d.querySelector(`#${id}-number`)].forEach(e=>e.oninput=()=>{if(e.validity.valid&&e.value!==''){state[id]=+e.value;state.preset='custom';render()}})});['counter','counter-number'].forEach(id=>document.querySelector(`#${id}`).oninput=e=>{if(e.target.validity.valid){state.counter=+e.target.value;state.preset='custom';render()}});document.querySelector('#construction').oninput=e=>{state.construction=e.target.value;state.preset='custom';render()};document.querySelector('#zero-style').oninput=e=>{state.zeroStyle=e.target.value;state.preset='custom';render()};document.querySelector('#preset').oninput=e=>{state.preset=e.target.value;if(presets[e.target.value])Object.assign(state,presets[e.target.value]);render()};document.querySelector('#specimen').oninput=render;document.querySelector('#compare').onclick=()=>{if(!snapshot){snapshot=JSON.stringify(currentProject());document.querySelector('#compare-status').textContent='A captured; edit controls to compare B.'}else{document.querySelector('#compare-status').textContent=snapshot===JSON.stringify(currentProject())?'A and B are identical.':'A/B differ; both source snapshots are controlled project JSON.'}};document.querySelector('#download-project').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(currentProject(),null,2)+'\n'],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='pfl-phase-1b-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),0)}}
async function init(){project=await (await fetch(new URL('../fontlab/project.json',import.meta.url))).json();glyphs=[...Array.from({length:95},(_,i)=>String.fromCodePoint(32+i)), ' ',...cu,...cl,'́','̈'].map(c=>({char:c,name:name(c),id:`${c.codePointAt(0).toString(16).padStart(4,'0')}`,upper:c===c.toUpperCase()&&c!==c.toLowerCase(),mark:'́̈'.includes(c),kind:/\d/.test(c)?'digit':/[A-Za-zА-Яа-яЁё]/.test(c)?'letter':'common'}));Object.assign(state,project.axes,{counter:project.localOverrides.O.counter,construction:project.switches.aConstruction,zeroStyle:project.switches.zeroStyle,preset:project.activePreset});document.querySelector('#coverage').textContent=`${glyphs.length} glyphs`;controls();window.pfl={glyphs,currentProject,evalGlyph};render()};init().catch(e=>document.querySelector('#preview-error').textContent=e.message);
